export const Protein = [
    "Chicken",
    "Turkey",
    "Sausage",
    "Ground Beef",
    "Steak",
    "Pork Loin",
    "Ground Pork",
    "Burgers",
    "Bacon",
    "Salmon",
    "Tilapia",
    "Halibut",
    "Shrimp",
    "Tuna",
    "Hummus",
    "Tofu",
    "Tempeh",
    "Black Beans",
    "Lentils",
    "Chickpeas",
];

export const Fruit = [
    "Apple",
    "Banana",
    "Strawberry",
    "Cherry",
    "Watermelon",
    "Canteloupe",
    "Grape",
    "Lychee",
    "Orange",
    "Grapefruit",
    "Blueberry",
    "Raspberry",
    "Blackberry",
    "Papaya",
    "Lemon",
    "Pineapple",
    "Fig",
    "Lime",
    "Plum",
    "Apricot",
];

export const Vegetables = [
    "Lettuce",
    "Cabbage",
    "Bell Pepper",
    "Zuchini",
    "Potato",
    "Carrot",
    "Cauliflower",
    "Onion",
    "Avocado",
    "Grean Bean",
    "Edamame",
    "Eggplant",
    "Mushroom",
    "Asparagus",
    "Pumpkin",
    "Tomato",
    "Spinach",
    "Celery",
    "Leek",
    "Cucumber",
];

export const Dairy = [
    "Milk",
    "Mozzarella",
    "Feta",
    "Sour Cream",
    "Yogurt",
    "Eggs",
    "Cottage Cheese",
    "Ricotta Cheese",
    "Ice Cream",
    "Condensed Milk",
    "Butter"
];

export const Other = [
    "Cheetos",
    "Cereal",
    "Oreos",
    "Bread",
    "Curry",
    "Coconut Milk",
    "Kimchi",
    "Soy Sauce",
    "Chili Oil",
    "Taco Shells",
    "Flour",
    "Chocolate Chips",
    "Caramel",
    "Lemon Curd",
    "Almond Flour"
];
